New guestbook
PavelSPN/GuestBook pull request #5
Opened 2018-06-11 10:12 UTC by PavelSPN

2018-06-11 14:26 UTC, egorbogatyrev requested changes

2018-06-11 14:26 UTC, egorbogatyrev commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@PavelSPN всю папку .idea лучше не комитить, это не нужно

2018-06-11 14:26 UTC, egorbogatyrev commented on css/guestbook.css
> +.push_button {
имена классов разделяются с помощью дефисов,  а не `_`

2018-06-11 14:26 UTC, egorbogatyrev commented on css/guestbook.css
> +  width:80px;
добавляй отступ между двоеточием и значением`:80px`
проверь весь css файл

2018-06-11 14:26 UTC, egorbogatyrev commented on css/guestbook.css
> +}
разделяй описание стилей для классов 1 пустой строкой, а то сейчас где-то разделено, где -то нет

2018-06-11 14:26 UTC, egorbogatyrev commented on css/guestbook.css
> +
внутри описания стиля не должно пустых строк

2018-06-11 14:26 UTC, egorbogatyrev commented on css/guestbook.css
> +
убрать пустую строку

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +  $uri = preg_split("[/]", $uri);
что это за хрень? убрать, оставить как было
`return '/' . ltrim($uri, '/');`

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +    // @todo Create callback for login.
callback уже создан, убрать коммент с todo

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +    'logout' => array(
`/logout` вернуть назад

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +    'delete_message' => array(
маппинг ассоциирует часть пути с конкретным колбеком, поэтому путь должен выглядеть как путь, а не как функция. `delete_message` - неудачное название части пути, лучше `/message/delete`, т.е. в этом духе

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +    // @todo Create callback for save message.
убрать все лишние, ни к чему не относящиеся комментарии

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +    'guestbook_sm' => array(
аналогично, путь непонятный, что за sm? если сохранение, то придерживайся единого стиля `/message/save`

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +      'time'=> time(),
перепроверить все оступы

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +  //unset($user_data['password']);
зачем закоментил?

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +  if (isset($_POST['signout'])) {
зачем эта проверка? если ты попал на этот колбек, то это значит юзер уже разлогинивается, чисти сессию и редиректи на главную

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +    unset ($_SESSION['user']);
это можно перенести в функцию `guestbook_unsetcookie` и ` unset ($_SESSION['time']);` тоже

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> + * @param $lim
корректная запись параметров
`@param int $lim`
`@param string $link2`

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.sql.inc
> +  $query = mysqli_query(guestbook_sql_connect(), 'SELECT * FROM `share`');
делай выборку кол-ва сразу в бд `SELECT COUNT(*) as count FROM ...`

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +    $_GET['guestbook_curr_link'] = 1;
сократи название, например дай имя ключу `page`

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +  if ($_GET['guestbook_curr_link'] > ceil($all / $lim)) {
для сокращения кода, можно объединить два условия
`if (!isset($_GET['guestbook_curr_link']) || ($_GET['guestbook_curr_link'] > ceil($all / $lim))) {
   $_GET['guestbook_curr_link'] = 1;
`

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +  $curr_link = $_GET['guestbook_curr_link'];
соответств. дать название переменной `$page`, `$page_first`, `$page_last`

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +    print $sled;
ничего в ней не принтуй, просто формируй массив страниц и возвращай его, принтовать навигацию нужно в темплейте

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +  if ($last < ceil($all / $lim) && ceil($all / $lim) - $last > 2) print "<a href='{$link2}?guestbook_curr_link={$y}'>...</a> ";
избегай такой сокращенной записи, это не best prectice

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +    $i_pred = $curr_link = 1;
избегай непонятных названий переменных

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.core.inc
> +    //If the current page is displayed, then it is assigned a special style css
в конце каждого комментария должна быть точка! после `//` обязательно идет пробел.

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.sql.inc
> +  if (isset($_GET['edit']) && $_GET['edit'] == 1) {
тут нужно проверять на существование id сообщения, если оно есть - то редактируешь, если нет - то новое

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.sql.inc
> +    if (isset($_POST['Guestbook_user_message_window']) && $_POST['Guestbook_user_message_window'] != NULL) {
что это за параметр? если сообщение то используй просто `message`, не нужно городить таких длинных названий, они сбивают с толку

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.sql.inc
> +  if ($new == FALSE) {
тут можно просто указать `else`

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.sql.inc
> +      header('Location: /');
если тебе нужен редирект так он уже реализован, используй функцию

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.sql.inc
> +      $query->execute();
используй транзакции и `try catch`

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.sql.inc
> +        header('Location: /?guestbook_curr_link=' . $_GET['guestbook_curr_link']);
функция редиректа уже есть

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.sql.inc
> +  if (isset($_GET['edit']) && $_GET['edit'] == 2) {
нужно получать айди мессаджа, и по нему удалять, а не хардкодать значение 2

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.theme.inc
> +  $vars['messages'] = guestbook_get_messages(); //записывает все сообщения из книги.
не записыает а получает наверное

2018-06-11 14:26 UTC, egorbogatyrev commented on includes/guestbook.theme.inc
> +  //если isset($_SESSION['user']['name']) существует, то записать значение $_SESSION['user']['name'] иначе NULL.
все ненужные коменты убрать

2018-06-11 14:26 UTC, egorbogatyrev commented on templates/html.php
> +// Get all necessary theme variables.
объедини с предыдущими тегами `php`, нет необходимости их тут дублировать

2018-06-11 14:26 UTC, egorbogatyrev commented on templates/html.php
> +<?php if ($vars['messages']): ?>
отступы пропущены

2018-06-11 14:26 UTC, egorbogatyrev commented on templates/html.php
> +    <?php if ($vars['is_logged']): ?>
этот файл нужно разбить на куски и упростить, сделать свой шаблон для формы логина, для сообщений, а потом просто принтовать в нужном месте, т.е. примерно так
```
  <?php print $page_top; ?>
  <?php print $page; ?>
  <?php print $page_bottom; ?>
```

2018-06-11 16:02 UTC, PavelSPN commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Выполнил

2018-06-11 16:03 UTC, PavelSPN commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
исключил всю папку из комита . 
В файле .gitignore сделал записи:
echo ".idea","__pycache__" > .gitignore
echo "__pycache__" > .gitignore

2018-06-11 16:21 UTC, PavelSPN commented on css/guestbook.css
> +.push_button {
Исправил

2018-06-11 16:21 UTC, PavelSPN commented on css/guestbook.css
> +  width:80px;
исправил

2018-06-11 16:25 UTC, PavelSPN commented on css/guestbook.css
> +}
исправил

2018-06-11 16:26 UTC, PavelSPN commented on css/guestbook.css
> +
исправил

2018-06-11 16:26 UTC, PavelSPN commented on css/guestbook.css
> +
исправил

2018-06-19 12:19 UTC, PavelSPN commented on includes/guestbook.core.inc
> +  $uri = preg_split("[/]", $uri);
исправил

2018-06-19 12:21 UTC, PavelSPN commented on includes/guestbook.core.inc
> +    // @todo Create callback for login.
исправил

2018-06-19 12:21 UTC, PavelSPN commented on includes/guestbook.core.inc
> +    'logout' => array(
исправил

2018-06-19 12:59 UTC, PavelSPN commented on includes/guestbook.core.inc
> +    'delete_message' => array(
исправил

2018-06-19 12:59 UTC, PavelSPN commented on includes/guestbook.core.inc
> +    // @todo Create callback for save message.
исправил

2018-06-19 12:59 UTC, PavelSPN commented on includes/guestbook.core.inc
> +    'guestbook_sm' => array(
исправил

2018-06-19 14:24 UTC, PavelSPN commented on includes/guestbook.core.inc
> +  //unset($user_data['password']);
исправил

2018-06-19 14:26 UTC, PavelSPN commented on includes/guestbook.core.inc
> +  if (isset($_POST['signout'])) {
исправил

2018-06-19 14:28 UTC, PavelSPN commented on includes/guestbook.core.inc
> +    unset ($_SESSION['user']);
исправил

2018-06-19 14:33 UTC, PavelSPN commented on includes/guestbook.core.inc
> + * @param $lim
исправил

2018-06-20 12:52 UTC, PavelSPN commented on includes/guestbook.sql.inc
> +  $query = mysqli_query(guestbook_sql_connect(), 'SELECT * FROM `share`');
исправил

2018-06-20 12:57 UTC, PavelSPN commented on includes/guestbook.core.inc
> +    $_GET['guestbook_curr_link'] = 1;
исправил

2018-06-20 13:02 UTC, PavelSPN commented on includes/guestbook.core.inc
> +  if ($_GET['guestbook_curr_link'] > ceil($all / $lim)) {
исправил

2018-06-25 09:03 UTC, PavelSPN commented on includes/guestbook.core.inc
> +  $curr_link = $_GET['guestbook_curr_link'];
исправил

2018-06-25 09:04 UTC, PavelSPN commented on includes/guestbook.core.inc
> +    print $sled;
исправил

2018-06-25 09:05 UTC, PavelSPN commented on includes/guestbook.core.inc
> +  if ($last < ceil($all / $lim) && ceil($all / $lim) - $last > 2) print "<a href='{$link2}?guestbook_curr_link={$y}'>...</a> ";
исправил

2018-06-25 09:05 UTC, PavelSPN commented on includes/guestbook.core.inc
> +    $i_pred = $curr_link = 1;
исправил

2018-06-25 09:12 UTC, PavelSPN commented on includes/guestbook.core.inc
> +    //If the current page is displayed, then it is assigned a special style css
исправил

2018-06-25 09:12 UTC, PavelSPN commented on includes/guestbook.sql.inc
> +  if (isset($_GET['edit']) && $_GET['edit'] == 1) {
исправил

2018-06-25 09:13 UTC, PavelSPN commented on includes/guestbook.sql.inc
> +    if (isset($_POST['Guestbook_user_message_window']) && $_POST['Guestbook_user_message_window'] != NULL) {
исправил

2018-06-25 09:15 UTC, PavelSPN commented on includes/guestbook.sql.inc
> +  if ($new == FALSE) {
исправил

2018-06-25 09:15 UTC, PavelSPN commented on includes/guestbook.sql.inc
> +      header('Location: /');
исправил

2018-06-25 09:16 UTC, PavelSPN commented on includes/guestbook.sql.inc
> +        header('Location: /?guestbook_curr_link=' . $_GET['guestbook_curr_link']);
исправил

2018-06-25 09:18 UTC, PavelSPN commented on includes/guestbook.sql.inc
> +  if (isset($_GET['edit']) && $_GET['edit'] == 2) {
исправил

2018-06-25 09:19 UTC, PavelSPN commented on includes/guestbook.theme.inc
> +  $vars['messages'] = guestbook_get_messages(); //записывает все сообщения из книги.
исправил

2018-06-25 09:20 UTC, PavelSPN commented on includes/guestbook.theme.inc
> +  //если isset($_SESSION['user']['name']) существует, то записать значение $_SESSION['user']['name'] иначе NULL.
исправил

2018-06-25 09:23 UTC, PavelSPN commented on templates/html.php
> +// Get all necessary theme variables.
исправил

2018-06-25 09:25 UTC, PavelSPN commented on templates/html.php
> +<?php if ($vars['messages']): ?>
это так специально, т.к. если сделать отступы, то они появляются в окне ввода сообщения.

2018-10-09 11:06 UTC, merged